name: Create Disk Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y dosfstools mtools

    - name: Create disk image file
      run: |
        # Create an empty disk image file
        dd if=/dev/zero of=disk_image.img bs=1M count=100

        # Format the image with a FAT32 file system
        mkfs.fat -F 32 disk_image.img

    - name: Mount the disk image
      run: |
        mkdir /mnt/tmp_mount
        sudo mount -o loop disk_image.img /mnt/tmp_mount

    - name: Copy files to disk image
      run: |
        sudo cp -r disk_image_contents/* /mnt/tmp_mount/

    - name: Unmount the disk image
      run: |
        sudo umount /mnt/tmp_mount
        rmdir /mnt/tmp_mount

    - name: Upload disk image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: disk-image
        path: disk_image.img

