name: Create SD Card Image
on: [push]
jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create image
        run: |
          ls
          pwd
          dd if=/dev/zero of=disk_image.img bs=1M count=100
          mkfs.fat -F 32 disk_image.img

      - name: Mount new image
        id: mount-image
        uses: damianperera/mount-image-action@v1
        with:
          imagePath: disk_image.img
          mountPoint: /mnt/tmp_mount

      - name: Write files to mounted image
        run: echo "Doing something"

      - name: Unmount new image
        uses: damianperera/unmount-image-action@v1
        with:
          imagePath: disk_image.img
          bootDeviceMapper: ${{ steps.mount-image.outputs.bootDeviceMapper }}
          rootDeviceMapper: ${{ steps.mount-image.outputs.rootDeviceMapper }}


          # - uses: actions/upload-artifact@v4
          #   with:
          #     name: my-artifact
          #     path: path/to/artifact/world.txt
